# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20170323_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_time'], 'permissions': (('can_comment', 'Can comment'),)},
        ),
    ]
